### ISSUE TITLE
Loaded into right hand column

### ISSUE THREAD

**Issue by kevfrost** [twibiral/ObsiDOOM#4]
Download and it launched in the right hand column of my obsidian set up.  No apparent way to move it to the centre.

**Comment by twibiral** [comment]
Yes, that's the way it is implemented. 

But you basically want to request a new feature, which is to embed it in the notes?

**Comment by kevfrost** [comment]
Ah, was unclear if this was intended as I keep my right hand column tiny and couldn't see most of the content. Will retry

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by twibiral** [comment]
You can just make the right side thing bigger

**Comment by kevfrost** [comment]
In expanding this on desktop, I got to see all the functionality on the right hand side, including the full screen option so all is great and I've been able to play GTA 1 for the first time in 20 years. I think this would be useful to explain in the documentation?
